CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "username" VARCHAR UNIQUE,
  "age" int,
  "email" varchar UNIQUE NOT NULL,
  "password" TEXT NOT NULL,
  "address" text NOT NULL,
  "contact" varchar NOT NULL,
  "gender" varchar,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "hotel" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "address" text NOT NULL,
  "contact" varchar NOT NULL
);

CREATE TABLE "dishes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "type" varchar,
  "price" decimal NOT NULL,
  "hotel_id" int
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "hotel_id" int,
  "order_time" timestamptz NOT NULL DEFAULT now(),
  "status" varchar CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  "total_amount" decimal
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "food_id" int,
  "quantity" int
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "payment_mode" varchar,
  "status" varchar,
  "payment_time" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "dishes" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("food_id") REFERENCES "dishes" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
