// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Dish struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Type    sql.NullString `json:"type"`
	Price   string         `json:"price"`
	HotelID sql.NullInt32  `json:"hotel_id"`
}

type Hotel struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Email   string `json:"email"`
	Address string `json:"address"`
	Contact string `json:"contact"`
}

type Order struct {
	ID          int32          `json:"id"`
	UserID      sql.NullInt32  `json:"user_id"`
	HotelID     sql.NullInt32  `json:"hotel_id"`
	OrderTime   time.Time      `json:"order_time"`
	Status      sql.NullString `json:"status"`
	TotalAmount sql.NullString `json:"total_amount"`
}

type OrderItem struct {
	ID       int32         `json:"id"`
	OrderID  sql.NullInt32 `json:"order_id"`
	FoodID   sql.NullInt32 `json:"food_id"`
	Quantity sql.NullInt32 `json:"quantity"`
}

type Payment struct {
	ID          int32          `json:"id"`
	OrderID     sql.NullInt32  `json:"order_id"`
	PaymentMode sql.NullString `json:"payment_mode"`
	Status      sql.NullString `json:"status"`
	PaymentTime time.Time      `json:"payment_time"`
}

type User struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Username  sql.NullString `json:"username"`
	Age       sql.NullInt32  `json:"age"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Address   string         `json:"address"`
	Contact   string         `json:"contact"`
	Gender    sql.NullString `json:"gender"`
	CreatedAt time.Time      `json:"created_at"`
}
